name: publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Publish extension
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Get release version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Create archive
      run: zip -r Overseerr-Assistant_${{ env.RELEASE_VERSION }}.zip . -x '*.git/*' '*images/screenshot-*.png'

    - name: Upload & release
      uses: mnao305/chrome-extension-upload@v4.0.1
      with:
        extension-id: hopnjiadheaagfhpipecoamoegijhnij
        client-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        refresh-token: ${{ secrets.REFRESH_TOKEN }}
        file-path: Overseerr-Assistant_${{ env.RELEASE_VERSION }}.zip
        publish: true
